# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account_create_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountCreateDialog(object):
    def setupUi(self, AccountCreateDialog):
        AccountCreateDialog.setObjectName("AccountCreateDialog")
        AccountCreateDialog.resize(503, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/app_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccountCreateDialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(AccountCreateDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 290, 481, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(AccountCreateDialog)
        self.buttonBox.accepted.connect(AccountCreateDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AccountCreateDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AccountCreateDialog)

    def retranslateUi(self, AccountCreateDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountCreateDialog.setWindowTitle(_translate("AccountCreateDialog", "Create Account"))
from . import resources_rc
